language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - pypy
install:
    - travis_retry pip install .
    - travis_retry pip install zope.testing
script:
    - python setup.py test -q
notifications:
    email: false
